version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend     # Point to the backend folder
      dockerfile: Dockerfile
    ports:
      - "3003:5000"
    volumes:
      - ./backend/:/app       # Mount backend directory to /app in container
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
      - PYTHONPATH=/app  # Add this line
    depends_on:
      - db
    command: sh -c "sleep 10 && python run.py"  # Wait for DB to be ready

  frontend:
    build:
      context: ./frontend    # Point to the frontend folder
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app      # Mount frontend directory to /app in container
      - /app/node_modules     # Optional: prevent conflicts with local node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend  # Ensure frontend starts after backend
    command: sh -c "ng analytics off && ng serve --host 0.0.0.0" # Ensure it binds to 0.0.0.0

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres-data:
